<a name="top"></a>
<div style="width:1000 px">

<div style="float:right; width:98 px; height:98px;">
<img src="https://cdn.miami.edu/_assets-common/images/system/um-logo-gray-bg.png" alt="Miami Logo" style="height: 98px;">
</div>

<h2>MPO 624: Assignment for Maximum Covariance Analysis </h2>
<h3> MCA, SVD, and eigenvector-eigenvalue diagonalization </h3>

<div style="clear:both"></div>
</div>

<hr style="height:2px;">

### Author: Wei-Ming Tsai
### Date: 04/24/2018


### 1.2 (a) decompose and reconstruct [2x3] matrix by SVD

In [47]:
import numpy as np
from netCDF4 import Dataset

In [48]:
a=np.array([[2,3],[3,4],[5,2]]); # original matrix
print('original matrix= \n',a)

original matrix= 
 [[2 3]
 [3 4]
 [5 2]]


In [49]:
u,s,vt = np.linalg.svd(a);
print('u=',u);print('')
print('vt=',vt);print('')
print('s=',s)

u= [[-0.44094186 -0.43499204 -0.78508102]
 [-0.62018087 -0.48463651  0.61684937]
 [-0.64880349  0.75888693 -0.05607722]]

vt= [[-0.76114325 -0.64858381]
 [ 0.64858381 -0.76114325]]

s= [7.86506846 2.26731078]


In [50]:
smat=np.zeros([3,2])
smat[0:2,0:2]=np.diag(s)
b=np.matmul(u,np.matmul(smat,vt)) # reconstruct 
print('reconstructed matrix= \n',b)

reconstructed matrix= 
 [[2. 3.]
 [3. 4.]
 [5. 2.]]


### 1.2 (b) 2x2 and 3x3 convariance matrices

#### 1. [2 x 2] convariance matrix reconstruction by eigen method and SVD

In [51]:
a=np.array([[3,1],[1,4]])
cov1=np.cov(a)
print('cov by cov function = \n',cov1);print('')

am=np.mean(a,1)
ap=a-np.array([[am[0]],[am[1]]]) # variance
print('cov by DDT = \n',np.matmul(ap,transpose_matrix(ap)));print('')

u,s,vt=np.linalg.svd(ap)
smat=np.zeros([2,2])
smat[0:2,0:2]=np.diag(s)
tmp=np.matmul(u,smat);tmp2=np.matmul(transpose_matrix(smat),transpose_matrix(u)); # U S ST UT
re=np.matmul(tmp,tmp2)
print('SVD reconstruction = \n',re)

cov by cov function = 
 [[ 2.  -3. ]
 [-3.   4.5]]

cov by DDT = 
 [[ 2.  -3. ]
 [-3.   4.5]]

SVD reconstruction = 
 [[ 2.  -3. ]
 [-3.   4.5]]


#### 2. [3x3]  convariance matrix reconstruction by eigen method and SVD

In [52]:
a=np.array([[3,1,5],[1,2,4],[2,4,3]])
cov1=np.cov(a) # convariance matrix
print('cov matrix = \n',cov1);print('')
am=np.mean(a,1)
ap=a-np.array([[am[0]],[am[1]],[am[2]]])
print('cov by DDT = \n',np.matmul(ap,transpose_matrix(ap)));print('')

u,s,vt=np.linalg.svd(ap)
smat=np.zeros([3,3])
smat[0:3,0:3]=np.diag(s)
tmp=np.matmul(u,smat);tmp2=np.matmul(np.transpose(smat),np.transpose(u)); # U S ST UT
re=np.matmul(tmp,tmp2)
print('SVD reconstruction = \n',re)

cov matrix = 
 [[ 4.          2.         -1.        ]
 [ 2.          2.33333333  0.5       ]
 [-1.          0.5         1.        ]]

cov by DDT = 
 [[ 8.          4.         -2.        ]
 [ 4.          4.66666667  1.        ]
 [-2.          1.          2.        ]]

SVD reconstruction = 
 [[ 8.          4.         -2.        ]
 [ 4.          4.66666667  1.        ]
 [-2.          1.          2.        ]]


In [53]:
v,e=np.linalg.eig(cov1); # eigenvalue, eigenvector
cov_re=np.matmul(np.matmul(e,np.diag(v)),np.linalg.inv(e))
print('cov_re = \n',cov_re)

cov_re = 
 [[ 4.          2.         -1.        ]
 [ 2.          2.33333333  0.5       ]
 [-1.          0.5         1.        ]]


#### Now try DD$^{T}$ instead of covariance

In [54]:
v,e=np.linalg.eig(np.matmul(ap,np.transpose(ap))); # eigenvalue, eigenvector
cov_re=np.matmul(np.matmul(e,np.diag(v)),np.linalg.inv(e))
print('DDT = \n',np.matmul(ap,np.transpose(ap)));print('')
print('cov_re = \n',cov_re)

DDT = 
 [[ 8.          4.         -2.        ]
 [ 4.          4.66666667  1.        ]
 [-2.          1.          2.        ]]

cov_re = 
 [[ 8.          4.         -2.        ]
 [ 4.          4.66666667  1.        ]
 [-2.          1.          2.        ]]


#### Summary
The SVD decomposition returns 3 matrices, while the eigen method returns two instead.

The SVD decomposition is available for non-squared matrices, while the eigen method works only if the operated matrix is squared (because the eigenvalue matrix must be diagonal). 

For a 2 by 2 matrix, covariance matrices constructed by COV, DDT and SVD are the same, but this result is not shown given a 3 by 3 matrix. For a 3 by 3 case, elements in covaraince matrix by DDT and SVD become double ,comparing to the correct one. That is because DDT should be divided by N-1 to form a real convairance matrix. 

If we put DD$^T$ in the eigen method, the original matrix DD$^T$ can be reconstructed by eigenvalue and eigenvector matrices (eve^-1).